// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sszrjgjothzvqbrrxhyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzenJqZ2pvdGh6dnFicnJ4aHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDU4MzAsImV4cCI6MjA2MTQyMTgzMH0.4aB4-X4vC_GFOro6IHqGhaXV7kD-ddeAlwj8hYBJJxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);